# Working Time - Start All Services
# รันคำสั่งนี้: .\start.ps1

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Working Time - Starting Services" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

# Get local IP address
$localIP = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notmatch "Loopback" -and $_.IPAddress -notmatch "^169" } | Select-Object -First 1).IPAddress
Write-Host "`nLocal IP: $localIP" -ForegroundColor Yellow

# Update .env file in Frontend
$envFile = "Front-End\.env"
$envContent = "# Auto-generated by start.ps1`nEXPO_PUBLIC_API_URL=http://${localIP}:8000"
Set-Content $envFile $envContent
Write-Host "Updated Frontend .env: EXPO_PUBLIC_API_URL=http://${localIP}:8000" -ForegroundColor Green

# Start Backend with Docker
Write-Host "`n[1/2] Starting Backend (Docker)..." -ForegroundColor Yellow
Push-Location "Back-End"
docker-compose up -d --build
Pop-Location

# Wait for backend to be ready
Write-Host "Waiting for Backend to be ready..." -ForegroundColor Yellow
Start-Sleep -Seconds 10

# Check if backend is running
try {
    $response = Invoke-WebRequest -Uri "http://localhost:8000/docs" -UseBasicParsing -TimeoutSec 5
    Write-Host "Backend is running!" -ForegroundColor Green
} catch {
    Write-Host "Backend may still be starting..." -ForegroundColor Yellow
}

# Start Frontend with Expo
Write-Host "`n[2/2] Starting Frontend (Expo)..." -ForegroundColor Yellow
Push-Location "Front-End"
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  Scan QR Code with Expo Go app" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
npx expo start --tunnel
Pop-Location
